#?????????
server:
  port: 8081
  servlet:
    context-path: /wm
#??mybatis
mybatis:
  #扫描所有mapper里的所有.xml文件--+++++++++++
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo
  configuration:
    map-underscore-to-camel-case: true
    #可以看所传的mysql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://${ip}:3306/wm?serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-circular-references: true
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ip: localhost